# Generated by Django 6.0.5 on 2026-05-26 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'crops',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='IrrigationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('irrigation_date', models.DateField()),
                ('water_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'irrigation_plans',
            },
        ),
    ]
