# Generated by Django 6.0.5 on 2026-05-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='core.company'),
        ),
        migrations.AddField(
            model_name='cleaningteam',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_teams', to='core.company'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='cleaning.cleaningtask'),
        ),
    ]
