# Generated by Django 6.0.5 on 2026-05-27 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
        ('transport', '0003_driver_pin_driver_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_points', to='core.company')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_points', to='transport.transportroute')),
            ],
            options={
                'db_table': 'et_assembly_point',
            },
        ),
        migrations.AddField(
            model_name='employeetransportinfo',
            name='assembly_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_infos', to='transport.assemblypoint'),
        ),
    ]
