# Generated by Django 6.0.5 on 2026-05-27 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
        ('transport', '0004_assemblypoint_employeetransportinfo_assembly_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=255)),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('transport_type', models.CharField(default='باص', max_length=50)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('requested_time', models.TimeField(blank=True, null=True)),
                ('request_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('supervisor_approved', 'Supervisor Approved'), ('manager_approved', 'Manager Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='transport.driver')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='transport.vehicle')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='core.company')),
            ],
            options={
                'db_table': 'et_transport_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
