# Generated by Django 6.0.5 on 2026-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transportrequest_employee_id_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransportinfo',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
