# Generated by Django 6.0.5 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_employee_pin_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
