# Generated by Django 6.0.5 on 2026-05-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transport_request_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('manager_pending', 'بانتظار المدير'), ('in_progress', 'تحت التنفيذ'), ('completed', 'مكتملة'), ('rejected', 'مرفوضة')], default='pending', max_length=20),
        ),
    ]
