# Generated by Django 6.0.5 on 2026-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_request_status_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='requester_section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
