# Generated by Django 6.0.5 on 2026-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_transportrequest_requester_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='distance_traveled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المسافة المقطوعة (كم)'),
        ),
    ]
