# Generated by Django 6.0.5 on 2026-05-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_transportrequest_distance_traveled'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('باص', 'باص'), ('دينة', 'دينة'), ('سيارة', 'سيارة'), ('دراجة', 'دراجة'), ('شاحنة', 'شاحنة'), ('أخرى', 'أخرى')], default='باص', max_length=50),
        ),
    ]
