# Generated by Django 6.0.5 on 2026-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bus_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الباص'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='معدل استهلاك الوقود (كم/لتر)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_purpose',
            field=models.CharField(blank=True, choices=[('توصيل الموظفين', 'توصيل الموظفين'), ('توصيل مشتريات', 'توصيل مشتريات'), ('توصيل خدمات', 'توصيل خدمات'), ('توصيل مخلفات', 'توصيل مخلفات'), ('سيارة نقل صغير', 'سيارة نقل صغير'), ('اسعاف', 'اسعاف'), ('اطفاء', 'اطفاء'), ('توصيل خياطات', 'توصيل خياطات')], default='', max_length=50, verbose_name='غرض المركبة'),
        ),
    ]
