# Generated by Django 6.0.5 on 2026-05-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_vehicle_bus_purpose_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الوصول الفعلي'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fuel_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوقود المستهلك (لتر)'),
        ),
    ]
