# Generated by Django 6.0.5 on 2026-05-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_email_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('company_admin', 'Company Admin'), ('department_user', 'Department User'), ('driver', 'Driver'), ('service_requester', 'طلب خدمة')], default='department_user', max_length=50),
        ),
    ]
